update-core:
  enabled: true

  # Values: Geyser-BungeeCord, Geyser-Fabric, Geyser-Spigot, Geyser-Standalone, Geyser-Velocity, Geyser-ViaProxy
  geyser-type: "Geyser-Standalone"

  # Change the URL with the type of your Geyser instance, this URL is only for standalone version.
  download-url: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone"

extensions:
  - download-url: "https://github.com/frafol/GeyserAutoUpdate/releases/latest/download/GeyserAutoUpdate.jar"
    target-file: "GeyserAutoUpdate.jar"
#  - download-url: "https://github.com/MCXboxBroadcast/Broadcaster/releases/latest/download/MCXboxBroadcastStandalone.jar"
#    target-file: "MCXboxBroadcastExtension.jar"
